back-command: bossshop open cosmetics %player%
back-item:
  name: "&cBack"
  material: RED_STAINED_GLASS_PANE
next-item:
  name: "&fNext Page"
  material: ARROW
previous-item:
  name: "&fPrevious Page"
  material: ARROW
text-selected: "&aSelected!"
text-unlocked: "&eClick to select!"
text-locked: "&cLocked"

mainmenu:
  playertrails:
    name: "&6Player Trails"
    material: BLAZE_POWDER
    lore:
      - "&7Show off with a wide selection of"
      - "&7particles and styles"
    slot: 20
  projectiletrails:
    name: "&6Projectile Trails"
    material: SPECTRAL_ARROW
    lore:
      - "&7Effects added to all projectiles,"
      - "&7including arrows, eggs, snowballs,"
      - "&7potions, and more."
    slot: 22
  wings:
    name: "&dWings"
    material: ELYTRA
    lore:
      - "&7Wear majestic, particle wings to outshine"
      - "&7your friends and foes. Requires"
      - "&6&lDIVINE &7rank."
    slot: 24
  remove:
    name: "&cRemove All"
    material: BARRIER
    lore:
      - "&7Click to remove all currently selected"
      - "&7particles from your character."
    slot: 4
    
# Style types: https://javadoc.rosewooddev.io/PlayerParticles/dev/esophose/playerparticles/styles/DefaultStyles.html
# Particle options: https://javadoc.rosewooddev.io/PlayerParticles/dev/esophose/playerparticles/particles/ParticleEffect.html
# Use the getInternalStyleName() for all playertrails.style.styles entries!!!
playertrails:
  remove:
    name: "&cRemove Player Trail"
    material: BARRIER
    lore:
      - "&7Click to remove all player trail"
      - "&7particles from your character."
  style:
    item:
      name: "&7Current Style: &f&l%style%"
      lore:
        - "%style_switcher%"
        - ""
        - "&fClick to cycle"
    styles:
      normal:
        name: "Normal"
        permission: group.guest
  trails:
    soulflame:
      name: "&3Soul Flame"
      permission: trails.soulflame
      effect: SOUL_FIRE_FLAME
    melon:
      name: "&aMelon"
      material: MELON
      permission: trails.melon
      effect: ITEM
      data: MELON
    
projectiletrails:
  remove:
    name: "&cRemove Projectile Trail"
    material: BARRIER
    lore:
      - "&7Click to remove all projectile trail"
      - "&7particles from your character."
  trails:
    soulflame:
      name: "&3Soul Flame"
      permission: trails.projectile.soulflame
        
wings:
  remove:
    name: "&cRemove Wings"
    material: BARRIER
    lore:
      - "&7Click to remove all wings"
      - "&7particles from your character."
  trails:
    soulflame:
      name: "&3Soul Flame"
      permission: trails.wings.soulflame