main: com.leomelonseeds.ultimaparticles.UltimaParticles
name: UltimaParticles
version: "1.0"
api-version: 1.20
author: M310N
description: Wrapper plugin for PlayerParticles to provide a GUI for Ultima
depend: [ PlayerParticles ]
commands:
  playertrails: { }
  projectiletrails: { }
  wings: { }
